chore!(all): attempt to update beego to v2
mindoc-org/mindoc pull request #662
Opened 2021-03-23 13:57 UTC by roberChen

# DO NOT MERGE!

BREAKING CHANGE: beego has update to v2, and this version of mindoc IS
NOT TESTED AND STABLE!!!

2021-03-23 14:02 UTC, roberChen commented on cache/cache.go
> +	"github.com/astaxie/beego/logs"
note: this import path has not been changed, will fix this later

2021-03-23 14:12 UTC, roberChen commented on go.mod
> +	github.com/astaxie/beego v1.12.3
note: this will remove later

2021-03-24 12:25 UTC, roberChen commented
note:
the v2.0.1 of beego has bugs. For ```github.com/mindoc-org/mindoc/commands.RegisterModel()```, this function calls ```github.com/beego/beego/v2/adapter/orm.RegisterModelWithPrefix(...)```, in v2.0.1, the function has a bug, which has been fixed in https://github.com/beego/beego/pull/4386/

2021-03-24 14:28 UTC, roberChen commented
current build of new version seems failed to create new admin user and demo book when initializing database (when running ```mindoc install```), however, when created the database using master build and switch to this new version, logins are succeeded.

After investigation, using beego/v2 version cannot create user or book when install. The database remains empty after *trying to insert admin and demo book*. REASON STILL IN INVESTIGATION

2021-03-25 16:22 UTC, roberChen commented
# about orm api change in v2

v2 version of beego remove the o.Rollback api for transaction operation.
typically, in v1, you can write code like this:
```go
                o := orm.NewOrm()
                if err := o.Operateion(); err != nil {
                        o.Rollback()
                        ...
                }
```
however, in v2, this is not available. beego will handles the transaction in new way using
cluster. the new code is like below:
```go
                o := orm.NewOrm()
                if err := o.DoTx(func(ctx context.Context, txOrm orm.TxOrmer) error{
                        err := o.Operations()
                        if err != nil {
                                return err
                        }
                }); err != nil {
                        ...
                }
```
when operation failed, it will automatically calls o.Rollback() for TxOrmer.
more details see https://beego.me/docs/mvc/model/transaction.md

2021-03-26 07:46 UTC, roberChen commented on models/BookResult.go
> +		if err := adapter.ExecuteViewPathTemplate(&buf, "document/export.tpl", viewPath, map[string]interface{}{"Model": m, "Lists": item, "BaseUrl": conf.BaseUrl}); err != nil {
need change!

2021-03-27 15:01 UTC, gsw945 approved these changes
运行注意：本地运行，使用`http://127.0.0.1:8181/`访问时，需要修改配置文件`conf/app.conf`中的`enablexsrf`为`false`，否则**POST**请求(eg: 项目创建、文章创建等)会报xsrf错误。
考虑到一直以来(特别是无IT技术的)用户无需修改配置文件即可运行，升级beego版本到v2时，如果默认需要修改配置文件的行为，会给用户带来不便。
所以，建议将配置文件修改`enablexsrf`默认值设置为`false`，**README.md**文档或**wiki**中添加`enablexsrf`配置相关的安全性说明。

2021-03-28 01:37 UTC, LawyZheng commented
beego v2.0.1 still leaves some problems unfixed, such as the Cookie SameSite feature, according to https://github.com/beego/beego/issues/4367.
I'm not sure whether it will cause some problems in Mindoc, since many functions in Mindoc are based on Cookies.
Maybe it's better for us to wait until beego v2 becomes stable.
Or at least, merge this feature into the dev branch or Mindoc 3.0 branch, rather than the master branch.

2021-03-28 04:19 UTC, roberChen commented
> beego v2.0.1 still leaves some problems unfixed, such as the Cookie SameSite feature, according to [beego/beego#4367](https://github.com/beego/beego/issues/4367).
> I'm not sure whether it will cause some problems in Mindoc, since many functions in Mindoc are based on Cookies.
> Maybe it's better for us to wait until beego v2 becomes stable.
> Or at least, merge this feature into the dev branch or Mindoc 3.0 branch, rather than the master branch.

Actially I'm not using v2.0.1, there has several bugs on that version. I use the latest commit of beego v2, and the bug you've mensioned has been fixed.

2021-03-29 01:34 UTC, gsw945 approved these changes

2021-03-30 03:25 UTC, roberChen commented
@LawyZheng we could release a minor version marked as stable version and then develop on master branch later. Once this pr is merged, later development should based on this because beego v2 is quite a big difference compared with v1, so parallel dev is impossible

2021-03-30 03:30 UTC, wangbin8909 requested changes

2021-03-30 03:30 UTC, wangbin8909 commented on models/Member.go
> +	if web.AppConfig.DefaultBool("ldap_enable", false) {
这里把 == false 去掉了，是原来的有问题，还是修改的不对。

2021-03-30 03:30 UTC, wangbin8909 commented on commands/migrate/migrate.go
> +	dbdatabase,_ := web.AppConfig.String("db_database")
逗号后面加个空格

2021-03-30 03:46 UTC, roberChen commented on models/Member.go
> +	if web.AppConfig.DefaultBool("ldap_enable", false) {
是修改的不对。已修改

2021-03-30 03:47 UTC, roberChen commented on commands/migrate/migrate.go
> +	dbdatabase,_ := web.AppConfig.String("db_database")
已format

2021-04-01 02:23 UTC, gsw945 submitted a review, later dismissed

2021-04-01 03:49 UTC, roberChen commented
build failed. travis.ci are using dep which is failed.

2021-04-01 04:09 UTC, gsw945 commented
> build failed. travis.ci are using dep which is failed for missing Gopkg, see [here](https://travis-ci.com/github/mindoc-org/mindoc/builds/221865466#L233)
> 
> I think the travis.ci should at least update the mod manager. Also go version could update.

[`.travis.yml`](https://github.com/mindoc-org/mindoc/blob/master/.travis.yml) for [Travis CI](https://travis-ci.com/github/mindoc-org/mindoc) is Editting, please wait.

2021-04-01 09:30 UTC, gsw945 approved these changes

2021-04-03 06:08 UTC, wangbin8909 reviewed
ok

2021-04-03 06:36 UTC, wangbin8909 approved these changes
approve

2021-04-03 13:06 UTC, roberChen commented
@gsw945 could you please check and merge?

2021-04-06 01:49 UTC, LawyZheng approved these changes

2021-04-06 03:46 UTC, merged