add prev&next read
mindoc-org/mindoc pull request #941
Opened 2024-04-20 16:24 UTC by 3xxx

add preview&next read in default_read.tpl

2024-04-23 01:41 UTC, gsw945 requested changes
感谢贡献

2024-04-23 01:41 UTC, gsw945 commented on conf/app.conf.example
该文件是完整配置样例，请恢复

2024-04-23 01:41 UTC, gsw945 commented on controllers/DocumentController.go
> +	logs.Info(identify)
此处日志改为Debug比较好，功能稳定后建议删除

2024-04-23 01:41 UTC, gsw945 commented on win下编译.md
该文件意义不大(与README有重复)，建议删除

2024-04-27 03:04 UTC, 3xxx commented on controllers/DocumentController.go
> +	logs.Info(identify)
已经删除

2024-04-27 03:04 UTC, 3xxx commented on win下编译.md
已经删除

2024-04-27 03:04 UTC, 3xxx commented on conf/app.conf.example
已经恢复

2024-04-27 07:42 UTC, gsw945 requested changes

2024-04-27 07:42 UTC, gsw945 commented on conf/app.conf.example
恢复错误，且CI已验证失败

2024-04-28 14:07 UTC, 3xxx commented on conf/app.conf.example
已经修改好。

2024-05-07 05:05 UTC, gsw945 approved these changes

2024-05-09 05:33 UTC, merged